# The Configuration File for Steve's Minedit Plugin

PluginPrefix: "&6[Minedit]"
DefaultSubreddit: "popular"
BorderLength: 50
PostLimit: 4
CommentLimit: 2
CommentLength: 100
ImageHeight: 10

#Create an app here: https://www.reddit.com/prefs/apps
redditClientID: client_id
redditClientSecret: client_secret
redditRedirectURI: https://Steve-Tech.github.io/Minedit/redirect.html