name: MCeddit
main: me.steve8playz.mceddit.MCeddit
version: 2.0
description: A Simple way to link Minecraft with Reddit
author: Steve8Playz
api-version: 1.15
commands:
  Reddit:
    description: Look at Reddit in game
    usage: /<command> [subreddit]
    permission: MCeddit.view
    permission-message: You don't have permission to use this command!
    default: true
  RedditPost:
    description: Look at a Reddit post in game
    usage: /<command> <permalink>
    permission: MCeddit.view
    permission-message: You don't have permission to use this command!
    default: true
  LinkReddit:
    description: Link your Minecraft account with your Reddit Account
    usage: /<command> <reddit username> [player]
    permission: MCeddit.link
    permission-message: You don't have permission to use this command!
    default: false
